---
- hosts: all
  become: yes

  tasks:

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Copy index.html
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html